export const DEFAULT_PATH = "/React-Fundamental/"
export const ARCHIVE_PAGE_PATH = "/React-Fundamental/archives/"
export const ADD_PAGE_PATH = "/React-Fundamental/add/"
export const DETAIL_PAGE_PATH = "/React-Fundamental/detail/:id"
export const LANDING_PAGE_PATH = "/React-Fundamental/login"
export const NOT_FOUND_PATH = "/React-Fundamental/*"